### ISSUE TITLE
The area xpath is inconsistant

### ISSUE THREAD

**Issue by TardisBeaubien** [Musab005/Centris#1]
Hi,Cool project!

Listings sometimes list additional features. For example, see "Intergenerational" on this [listing](https://www.centris.ca/en/maison~a-vendre~brossard/27379958?view=Summary) that is absent from this [listing](https://www.centris.ca/en/maison~a-vendre~brossard/18634315?view=Summary). 

I'm using the following xpaths in the spider using Splash to capture the area and the built year:

```
        year = response.xpath('//div[@class="carac-title" and contains(string(), "Year built")]/parent::*//div[2]/span/text()').get()
        area = response.xpath('//div[@class="carac-title" and contains(string(), "Lot area")]/parent::*//div[2]/span/text()').get()
```

**Comment by Musab005** [comment]
Hi!
Thank you for the insight. I indeed messed up the area xpath. I have fixed it now and also cleaned up the code. The spider with Splash is now available under the name `listings_detailed` and can be run directly from the terminal using `scrapy crawl listings_detailed` or from the GUI application.

Thanks!
